[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "chmod -R 775 storage",
    "chmod -R 775 bootstrap/cache"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
PHP_VERSION = "8.2"
NODE_VERSION = "18"